version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "users"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vo31wjwfnz9a"
s3_prefix = "users"
region = "us-east-1"
profile = "staging"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "dataBaseConnection=\"mongodb+srv://userClusterDeltax:g1k0KThJrMpvnEMM@deltaxdb.airpm.mongodb.net/deltastaging\" ARNCognito=\"us-east-1_uR6LFXj4U\" ARNCognitoUsersOperator=\"arn:aws:cognito-idp:us-east-1:345062269307:userpool/us-east-1_uR6LFXj4U\" ARNCognitoUsersCarrier=\"arn:aws:cognito-idp:us-east-1:345062269307:userpool/us-east-1_7JlBMUgy1\" emailCognito=\"info@deltaxla.com\" ARNEmail=\"arn:aws:ses:us-east-1:345062269307:identity/info@deltaxla.com\" ARNSns=\"arn:aws:sns:us-east-1:345062269307:app/GCM/sendNotificationDeltaStaging\" IdGrupoCognitoCarrier=\"us-east-1_7JlBMUgy1\""
